source $HOME/.zsh/init.zsh
if [[ -f $HOME/.zplug/init.zsh ]] {
  source $HOME/.zplug/init.zsh

# zplug "plugins/git", from:oh-my-zsh
  zplug "plugins/hitokoto", from:oh-my-zsh
  zplug "plugins/extract", from:oh-my-zsh
  zplug "plugins/z", from:oh-my-zsh
  zplug "plugins/vi-mode", from:oh-my-zsh
  zplug "plugins/colored-man-pages", from:oh-my-zsh
  zplug "plugins/safe-paste", from:oh-my-zsh
  zplug "plugins/git-open", from:oh-my-zsh
  # zplug "plugins/thefuck", from:oh-my-zsh

  zplug "themes/ys", from:oh-my-zsh, as:theme

  zplug "zsh-users/zsh-syntax-highlighting"
  zplug "zsh-users/zsh-autosuggestions"

  zplug 'zplug/zplug', hook-build:'zplug --self-manage'

  if ! zplug check --verbose; then
      echo 'Run "zplug install" to install'
  fi
  # Then, source plugins and add commands to $PATH
  zplug load
} else {
  echo "\033[31mPlease install zplug.\033[0m"
  echo "\033[31mSee:https://github.com/zplug/zplug\033[0m"
}

