{ username, ... }: 

{
  nix.settings.trusted-users = [username];

  users.users."${username}" = {
    # the hashed password with salt is generated by run `mkpasswd`.
    hashedPassword = "$y$j9T$IsFQlC0ZcKypb6DxVtapO.$UQ4lTtOjyV95QLzp9nc7lMunvn8eY4oVKNUXyfz55xC";
    home = "/home/${username}";
    isNormalUser = true;
    description = username;
    extraGroups = [
      username
      "users"
      "networkmanager"
      "wheel"
      "docker"
      "adbusers"
      "light"
      "video"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAWzzDW+0ytfjSytMcESuf1CFiuRCnOBlNpw65wtsyk/o1DajVIWdwI4sGLOzk+oNncqJPiQQ7v5a43mjJJP9XFCa9ohiRgTIoHtiPllA+4Kqm6dson+Q0skvq9DV62Sv9gKaGAhmKyxTvxqIq71BGwzKiMO8jFuuD2+J+FqA4Bvkb/ygwWersdc5V7fZdid20iop7Zk+GV+G1+qRvqHlTAQDu8kcTlbqJri9Zd8/Xf1RjxMwfsyBKZH9uUjKGCJD7oGRlYggd+tZ1TfJ/FYcEi23jaYHgtmeWkmVs1ro69vtlXVm5+WGQ77RJrZeSVxMKQhYuQkpBsCeK+1hHlKix7VPG6iKyR2X1zbrqlonkN2TH9fr+8vCdDHdNS8n8yMi5qk9gKphB89ashPAa7LJdkXB2g6doYYB1Z8KTiD1/jsLglWIZwywRV+kSeUQT1L9zrskTysmcxXRhnHpygpQMuC4wxVhTdzroSkhep0V2Ap64mxd8eIZ4GQn3jaVTJ7M= i@mslxl.com"
    ];
  };
}