{lib}: {
  username = "mslxl";
  userfullname = "mslxl";
  useremail = "i@mslxl.com";

  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$GU..../....gu49Yu8t1prYUL4YO7PMZ/$kTX5FKbHNe3Noyc.trDrZaShhDFj2uFi1Lzfso7H883";

  mainSshAuthorizedKeys = [
    # The main ssh keys for daily usage
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF3yC/OTEyXuHv0G7zEUJma5n7MUL71z5lEIIiRVKB+R i@mslxl.com"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDHfqMNEo7m45aVorq8zzWEtqcR5DSwwLFbcATYORasz mslxl@nixos-wsl"
  ];

  secondaryAuthorizedKeys = [
    # the backup ssh keys for disaster recovery
  ];
}
